// Writes src/version.ts from package.json. Runs automatically on `npm version`.
import { readFileSync, writeFileSync } from 'node:fs';

const { version } = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'));
writeFileSync(
  new URL('../src/version.ts', import.meta.url),
  `// Generated by scripts/sync-version.mjs from package.json. Do not edit.\nexport const VERSION = '${version}';\n`,
);
